src/LITReview/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('review.urls', 'review'), namespace='review')),
    path('account/', include(('accounts.urls', 'auth_system'), namespace='auth_system')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from .views import new_account

urlpatterns = [
    path('new_account/', new_account, name='new_account'),
    path('auth/', auth_views.LoginView.as_view(template_name='accounts/auth.html', redirect_authenticated_user=True),
         name='auth'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

src/review/urls.py
from django.urls import path
from .views import index, new_ticket, subscription_page, DeleteSubscription, new_follow,\
    posts, EditTicket, DeleteTicket, CreateReview, DeleteReview, EditReview, create_ticket_and_review

urlpatterns = [
    path('', index, name='index'),
    path('posts', posts, name='posts'),
    path('update_ticket/<int:pk>/', EditTicket.as_view(), name='edit_ticket'),
    path('new_ticket/', new_ticket, name='new_ticket'),
    path('delete_ticket/<int:pk>/', DeleteTicket.as_view(), name='delete_ticket'),
    path('answer_ticket/<int:pk>/', CreateReview.as_view(), name='creation_review'),
    path('delete_review/<int:pk>/', DeleteReview.as_view(), name='delete_review'),
    path('update_review/<int:pk>/', EditReview.as_view(), name='update_review'),
    path('create_ticket_and_review/', create_ticket_and_review, name='create_ticket_and_review'),
    path('subscription/', subscription_page, name='subscription_page'),
    path(r'subscription/add/', new_follow, name='new_follow'),
    path("subscription/<int:pk>/delete_subscription/", DeleteSubscription.as_view(), name='delete_subscription')
]

src/review/models.py
from django.core.validators import MinValueValidator, MaxValueValidator
from django.conf import settings
from django.db import models


class Ticket(models.Model):
    title = models.CharField(max_length=128)
    description = models.TextField(max_length=2048, blank=True)
    user = models.ForeignKey(to=settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    image = models.ImageField(null=True, blank=True, upload_to='images/')
    time_created = models.DateTimeField(auto_now_add=True)


class Review(models.Model):
    ticket = models.ForeignKey(to=Ticket, on_delete=models.CASCADE)
    rating = models.PositiveSmallIntegerField(
        # validates that rating must be between 0 and 5
        validators=[MinValueValidator(0), MaxValueValidator(5)])
    headline = models.CharField(max_length=128)
    body = models.CharField(max_length=8192, blank=True)
    user = models.ForeignKey(
        to=settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    time_created = models.DateTimeField(auto_now_add=True)


class UserFollows(models.Model):
    user = models.ForeignKey(to=settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='following')
    followed_user = models.ForeignKey(to=settings.AUTH_USER_MODEL, on_delete=models.CASCADE,
                                      related_name='following_by')

    def __str__(self):
        message = '{} suit {}'.format(self.user, self.followed_user)
        return message

    class Meta:
        # ensures we don't get multiple UserFollows instances
        # for unique user-user_followed pairs
        unique_together = ('user', 'followed_user', )

src/review/forms.py
from django import forms
from .models import Ticket, Review


class NewTicketForm(forms.ModelForm):
    title = forms.CharField(label='Titre')

    class Meta:
        model = Ticket
        fields = ['title', 'description', 'image']


class NewReviewForm(forms.ModelForm):
    choices = [(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')]
    body = forms.CharField(label='Critique', widget=forms.Textarea, max_length=8192)
    headline = forms.CharField(label='Titre')
    rating = forms.TypedChoiceField(label='Note', widget=forms.RadioSelect(), choices=choices, coerce=int)

    class Meta:
        model = Review
        fields = ['rating', 'headline', 'body']

src/review/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.db.utils import IntegrityError
from django.views.generic import DeleteView, UpdateView, CreateView
from django.urls import reverse_lazy
from django.db import transaction
from django.core.exceptions import ObjectDoesNotExist
from .forms import NewTicketForm, NewReviewForm
from .models import UserFollows, Ticket, Review
from .review_functions import multi_request, review_already_exist, get_ticket_from_pk, \
    create_ticket_and_answer, create_ticket


@login_required
def index(request):
    section = "flux"
    posts_to_display = multi_request(feed=True, request=request)
    return render(request, 'review/index.html', {'ticket_button': True, 'section': section,
                                                 'posts_to_display': posts_to_display, 'range': range(5)})


@login_required
def posts(request):
    section = "posts"
    posts_to_display = multi_request(request=request)
    return render(request, 'review/index.html', {'ticket_button': True, 'section': section,
                                                 'posts_to_display': posts_to_display, 'range': range(5)})


@login_required()
def new_ticket(request):

    if request.method == 'POST':
        form = NewTicketForm(request.POST, request.FILES)
        if form.is_valid():
            create_ticket(request, form_ticket=form)
            return redirect('review:index')
    else:
        form = NewTicketForm()
    return render(request, 'review/new_ticket.html', {'form': form, 'page': request.path})


@login_required()
def subscription_page(request):

    section = 'subscription'

    return render(request, 'review/subscriptions.html', {'section': section,
                                                         'list_of_following_users': request.user.following.all(),
                                                         'list_of_followed_users': request.user.following_by.all()})


@login_required()
def new_follow(request):
    try:
        user_follow = User.objects.get(username=request.POST.get("subscribe_to"))
    except ObjectDoesNotExist:
        return redirect('review:subscription_page')
    if user_follow:
        if user_follow == request.user:
            return redirect('review:subscription_page')
        else:
            new_followed_user = UserFollows()
            new_followed_user.user = request.user
            new_followed_user.followed_user = user_follow
            try:
                new_followed_user.save()
            except IntegrityError:
                pass
            return redirect('review:subscription_page')


@method_decorator(login_required, name='dispatch')
class DeleteSubscription(DeleteView):
    model = UserFollows
    success_url = reverse_lazy('review:subscription_page')

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user=self.request.user)


@method_decorator(login_required, name='dispatch')
class EditTicket(UpdateView):
    model = Ticket
    fields = ('description', 'image', )
    template_name = 'review/new_ticket.html'

    def form_valid(self, form):
        ticket = form
        ticket.save()
        return redirect('review:index')

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user=self.request.user)


@method_decorator(login_required, name='dispatch')
class DeleteTicket(DeleteView):
    model = Ticket
    success_url = reverse_lazy('review:index')

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user=self.request.user)


@method_decorator(login_required, name='dispatch')
class CreateReview(CreateView):
    model = Review
    form_class = NewReviewForm
    success_url = reverse_lazy('review:index')
    template_name = 'review/new_review.html'
    context_object_name = 'review'

    def form_valid(self, form):
        review = form.save(commit=False)
        review.ticket = get_ticket_from_pk(self.kwargs['pk'])
        review.user = self.request.user
        review.save()
        return redirect('review:index')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        review_already_exist(self.kwargs['pk'])
        context['post'] = get_ticket_from_pk(self.kwargs['pk'])
        context['ticket_button'] = False
        context['page'] = 'new_review'
        return context


@method_decorator(login_required, name='dispatch')
class DeleteReview(DeleteView):
    model = Review
    success_url = reverse_lazy('review:index')

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user=self.request.user)


@method_decorator(login_required, name='dispatch')
class EditReview(UpdateView):
    model = Review
    form_class = NewReviewForm
    template_name = 'review/new_review.html'

    def form_valid(self, form):
        review = form
        review.save()
        return redirect('review:index')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['post'] = self.object.ticket
        context['ticket_button'] = False
        return context

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user=self.request.user)


@transaction.atomic
def create_ticket_and_review(request):

    if request.method == 'POST':
        form_ticket = NewTicketForm(request.POST, request.FILES)
        form_review = NewReviewForm(request.POST)
        if form_ticket.is_valid() and form_review.is_valid():
            create_ticket_and_answer(request, form_ticket, form_review)
            return redirect('review:index')

    form_ticket = NewTicketForm()
    form_review = NewReviewForm()
    form_ticket_list = [form_ticket]
    form_review_list = [form_review]
    return render(request, 'review/new_ticket_and_review.html',
                  context={'form_ticket_list': form_ticket_list, 'form_review_list': form_review_list})

src/review/templates/review/Review_confirm_delete.html
{% extends 'includes/delete_object.html'  %}
{% block message %}
<h1 class="fs-5 text-center">Souhaitez-vous vraiment supprimer votre critique?</h1>
{% endblock %}
{% block redirect_button %}
<button class="btn btn-primary m-1" type="button" onclick="window.location.href= '{% url 'review:index' %}'" >non</button>
{% endblock %}

src/review/templates/review/Ticket_confirm_delete.html
{% extends 'includes/delete_object.html'  %}
{% block message %}
<h1 class="fs-5 text-center">Souhaitez-vous vraiment supprimer votre demande de critique?</h1>
{% endblock %}
{% block redirect_button %}
<button class="btn btn-primary m-1" type="button" onclick="window.location.href= '{% url 'review:index' %}'" >non</button>
{% endblock %}

src/review/templates/review/UserFollows_confirm_delete.html
{% extends 'includes/delete_object.html'  %}
{% block message %}
<h1 class="fs-5 text-center">Souhaitez-vous vraiment vous désabonner de "{{ object.followed_user }}"?</h1>
{% endblock %}
{% block redirect_button %}
<button class="btn btn-primary m-1" type="button" onclick="window.location.href= '{% url 'review:subscription_page' %}'" >non</button>
{% endblock %}

src/review/templates/review/base.html
{% load static %}
<html lang='fr'>
  <head>
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <meta charset='UTF-8'>
      <title>LITReview</title>
      <link rel="stylesheet" type="text/css" href="{% static 'css/base_style.css' %}">
      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
      <link rel="stylesheet" href="https://maxst.icons8.com/vue-static/landings/line-awesome/line-awesome/1.3.0/css/line-awesome.min.css">
      <link rel="shortcut icon" href="/media/images/favicon/favicon.ico">
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script>
  </head>
  <body>
    <div class="d-flex flex-column h-100">
      <div class="row gx-0">
        <div class="col-12">
          <header>
            <nav class="navbar navbar-expand-lg navbar-light bg-light">
              <div class="container-fluid">
                {% if user.is_authenticated %}
                <div class="container-fluid">
                  <div class="row gx-0 flex-lg-row flex-row-reverse">
                    <div class="navbar-header d-flex flex-row col-lg-6 col-7">
                      <a class="navbar-brand ms-lg-auto" href="{% url 'review:index' %}">LITReview</a>
                    </div>
                {% else %}
                <div class="navbar-header d-flex flex-row col-12">
                  <a class="navbar-brand mx-auto" href="{% url 'review:index' %}">LITReview</a>
                {% endif %}
                {% if user.is_authenticated %}
                    <button class="navbar-toggler me-auto col-2 col-sm-1 ms-2" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                      <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="col-lg-6 col-12">
                      <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav ms-md-auto mb-2 mb-lg-0">
                          <li class="nav-item ms-2 ms-lg-0">
                            {% if section == 'flux' %}
                            <a class="nav-link active" aria-current="page" href="{% url 'review:index' %}">Flux</a>
                            {% else %}
                            <a class="nav-link" aria-current="page" href="{% url 'review:index' %}">Flux</a>
                            {% endif %}
                          </li>
                          <li class="nav-item ms-2 ms-lg-0">
                            {% if section == 'posts' %}
                            <a class="nav-link active" href="{% url 'review:posts' %}">Posts</a>
                            {% else %}
                            <a class="nav-link" href="{% url 'review:posts' %}">Posts</a>
                            {% endif %}
                          </li>
                          <li class="nav-item ms-2 ms-lg-0">
                            {% if section == 'subscription' %}
                            <a class="nav-link active" href="{% url 'review:subscription_page' %}">Abonnements</a>
                            {% else %}
                            <a class="nav-link" href="{% url 'review:subscription_page' %}">Abonnements</a>
                            {% endif %}
                          </li>
                          <li class="nav-item ms-2 ms-lg-0">
                            <a class="nav-link" id="deconexion" href="{% url 'auth_system:logout' %}">Se déconnecter</a>
                          </li>
                        </ul>
                      </div>
                    </div>
                  </div>
                </div>
                {% else %}
                </div>
                {% endif %}
              </div>
            </nav>
          </header>
        </div>
      </div>
      <div class="content-background row gx-0 justify-content-center flex-grow-1 flex_shrink-0 w-auto" style="background-color: rgb(233,233,233);">
        <div class="col-12">
          <div class="bg-white container d-flex h-100 justify-content-center">
            {% block body %}{% endblock %}
          </div>
        </div>
      </div>
      <div class="row gx-0 flex-shrink-0">
        <div class="col-12">
          <footer class="bg-light h-100">
            <p id="footer_message">LITReview_project</p>
          </footer>
        </div>
      </div>
    </div>
  </body>
</html>

src/review/templates/review/index.html
{% extends 'review/base.html'  %}
{% block body %}
	<div class="col-12 p-2">
		{% if section == 'flux' %}
		<div class="d-flex col-lg-9 col-12 m-2 justify-content-around mx-auto">
				<button class="btn-sm btn-outline-secondary col-lg-4 col-5 m-2" onclick="window.location.href= '{% url 'review:new_ticket' %}'"> Demander une critique</button>
				<button class="btn-sm btn-outline-secondary col-lg-4 col-5 m-2" onclick="window.location.href= '{% url 'review:create_ticket_and_review' %}'"> Créer une critique</button>
		</div>
		{% endif %}
		{% if not posts_to_display %}
		<div class="d-flex h-75">
			<div class="col-lg-8 col-12 border rounded align-self-center mx-auto">
				{% if section == 'flux' %}
				<h1 class="fs-4 text-center">Oups... on dirait que votre flux est vide!</h1>
				{% else %}
				<h1 class="fs-4 text-center">Oups... on dirait que vous n'avez aucun posts!</h1>
				{% endif %}
				<br>
				<div class="d-flex justify-content-around">
					<a href="{% url 'review:subscription_page' %}">s'abonner!</a>
					<a href="{% url 'review:create_ticket_and_review' %}">Créer une critique!</a>
					<a href="{% url 'review:new_ticket' %}">Créer un nouveau ticket!</a>
				</div>
			</div>
		</div>
		{% endif %}
		<div>
			{% for post in posts_to_display %}
			{% include 'includes/posts.html' %}
			{% endfor %}
		</div>
		<nav aria-label="...">
			<ul class="pagination justify-content-center">
			  	{% if posts_to_display.has_previous %}
			  	<li class="page-item text-center m-2"><a class="page-link" href="?page={{ posts_to_display.previous_page_number }}">Précédent</a></li>
			  	{% endif %}
			  	{% if posts_to_display.has_next %}
			  	<li class="page-item text-center m-2"><a class="page-link" href="?page={{ posts_to_display.next_page_number }}">Suivant</a></li>
			  	{% endif %}
			</ul>
  		</nav>
	</div>
{% endblock %}

src/review/templates/review/new_review.html
{% extends 'review/base.html'  %}
{% load static %}
{% block body %}
  <div class="col-8 border rounded m-3">
    <div class="border-bottom">
      <p>Vous êtes en train de poster en réponse à</p>
      <div class="m-2">
        {% include 'includes/posts.html' %}
      </div>
    </div>
    <div class="m-2">
      {% if page == 'new_review'%}
      <h1 class="fs-5 text-center">Créer une critique</h1>
      {% else %}
      <h1 class="fs-5 text-center">Modifier votre critique</h1>
      {% endif %}
        <form method="post" enctype="multipart/form-data">
          {% csrf_token %}
          {% include 'includes/form.html' %}
          <br>
          {% if page == 'new_review'%}
          <button type="submit" class="btn btn-primary float-end m-2">Envoyer</button>
          {% else %}
          <button type="submit" class="btn btn-primary float-end m-2">Modifier</button>
          <button type="button" class="btn btn-secondary float-end m-2 " onclick="window.location.href= '{% url 'review:index' %}'">Annuler</button>
          {% endif %}
        </form>
    </div>
  </div>
{% endblock %}

src/review/templates/review/new_ticket.html
{% extends 'review/base.html'  %}
{% load static %}
{% block body %}
  <div class="col-8">
    <br>
    {% if page == '/new_ticket/'%}
    <h1 class="fs-5 text-center">Créer un nouveau ticket</h1>
    {% else %}
    <h1 class="fs-5 text-center">Modifier votre ticket</h1>
    <p class="fs-5">Titre: {{ticket.title}}</p>
    {% endif %}
      <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% include 'includes/form.html' %}
        <br>
        {% if page == '/new_ticket/'%}
        <button type="submit" class="btn btn-primary float-end">Envoyer</button>
        {% else %}
        <button type="submit" class="btn btn-primary float-end">Modifier</button>
        <button type="button" class="btn btn-secondary float-end me-2 " onclick="window.location.href= '{% url 'review:index' %}'">Annuler</button>
        {% endif %}
      </form>
  </div>
{% endblock %}

src/review/templates/review/new_ticket_and_review.html
{% extends 'review/base.html'  %}
{% load static %}

{% block body %}
  <div class="col-8 border rounded m-3">
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      <div class="border-bottom">
        <div class="m-2">
          <h1 class="fs-5 text-center">Créer votre ticket</h1>
          {% for form in form_ticket_list %}
            {% include 'includes/form.html' %}
          {% endfor %}
        </div>
      </div>
      <div class="m-2">
        <h1 class="fs-5 text-center">Créer votre critique</h1>
          {% for form in form_review_list %}
            {% include 'includes/form.html' %}
          {% endfor %}
        <br>
        <button type="submit" class="btn btn-primary float-end m-2">Envoyer</button>
      </div>
    </form>
  </div>
{% endblock %}

src/review/templates/review/subscriptions.html
{% extends 'review/base.html'  %}
{% load static %}
{% block body %}
  <div class="col-10">
      <h1 class="text-center fs-4 m-3">Suivre d'autres utilisateurs</h1>
      <div>
          <form class="d-flex m-3 col-md-8 col-12 mx-auto" action="{% url 'review:new_follow' %}" method="post">
              {% csrf_token %}
              <input class="form-control me-2" type="search" placeholder="Nom d'utilisateur" aria-label="Search" name="subscribe_to" >
              <button class="btn btn-outline-success m-2" type="submit">Envoyer</button>
          </form>
      </div>
      <div>
          <h1 class="text-center fs-4 m-3">Abonnement(s)</h1>
          <ul class="h-25 border mx-auto col-md-8 col-12 list-unstyled overflow-scroll">
              {% for sub in list_of_following_users %}
              <li class="m-2">
                  <div class="w-100 border-bottom">
                      <div class="d-flex">
                         <p class="col-8">{{ sub.followed_user}} </p>
                        <div class="col-4 text-end">
                            <button class="btn-sm btn-danger align-middle" type="button" onclick="window.location.href= '{{sub.id}}/delete_subscription/'">Se désabonner</button>
                        </div>
                      </div>
                  </div>
              </li>
              {% endfor %}
          </ul>
      </div>
      <div class="justify-content-center">
          <h1 class="text-center fs-4 m-3">Abonné(es)</h1>
          <ul class="h-25 border mx-auto col-md-8 col-12 list-unstyled overflow-scroll">
              {% for sub in list_of_followed_users %}
              <li class="m-2 border-bottom">
                  <p class="col-12"> {{ sub.user }}</p>
              </li>
              {% endfor %}
          </ul>
      </div>
  </div>
{% endblock %}