src/LITReview/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('review.urls', 'review'), namespace='review')),
    path('account/', include(('accounts.urls', 'auth_system'), namespace='auth_system')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from .views import new_account

urlpatterns = [
    path('new_account/', new_account, name='new_account'),
    path('auth/', auth_views.LoginView.as_view(template_name='accounts/auth.html', redirect_authenticated_user=True),
         name='auth'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

src/review/urls.py
from django.urls import path
from .views import index, new_ticket, subscription_page, DeleteSubscription, new_follow,\
    posts, EditTicket, DeleteTicket, CreateReview, DeleteReview, EditReview, create_ticket_and_review

urlpatterns = [
    path('', index, name='index'),
    path('posts', posts, name='posts'),
    path('update_ticket/<int:pk>/', EditTicket.as_view(), name='edit_ticket'),
    path('new_ticket/', new_ticket, name='new_ticket'),
    path('delete_ticket/<int:pk>/', DeleteTicket.as_view(), name='delete_ticket'),
    path('answer_ticket/<int:pk>/', CreateReview.as_view(), name='creation_review'),
    path('delete_review/<int:pk>/', DeleteReview.as_view(), name='delete_review'),
    path('update_review/<int:pk>/', EditReview.as_view(), name='update_review'),
    path('create_ticket_and_review/', create_ticket_and_review, name='create_ticket_and_review'),
    path('subscription/', subscription_page, name='subscription_page'),
    path(r'subscription/add/', new_follow, name='new_follow'),
    path("subscription/<int:pk>/delete_subscription/", DeleteSubscription.as_view(), name='delete_subscription')
]

src/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login as auth_login


def new_account(request):
    if request.user.is_authenticated:
        return redirect('review:index')
    elif request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect('review:index')
    else:
        form = UserCreationForm
    return render(request, 'accounts/new_account.html', {'form': form})

src/accounts/templates/accounts/auth.html
{% extends 'review/base.html'  %}
{% load static %}
{% block body %}
<div class="col-12 d-flex flex-column-reverse flex-md-row justify-content-around">
  <div class="col-md-6 col-12 align-self-md-center">
    <br>
    <h1 class="fs-5 text-center">Inscrivez-vous maintenant</h1>
    <br>
    <div class="text-center mb-2 mb-md-0">
      <input type="hidden" name="next" value="{{ next }}">
      <button type="submit" class="btn btn-primary" onclick="window.location.href= '{% url 'auth_system:new_account' %}'">S'inscrire !</button>
    </div>
  </div>
  <div class="col-md-6 col-12 justify-content-center align-self-md-center">
    <br>
    <h1 class="fs-5 text-center">Connectez-vous !</h1>
    <br>
      <form method="post" class="col-md-6 col-8 mx-auto">
        {% csrf_token %}
        {% include 'includes/form.html' %}
        <br>
        <button type="submit" class="btn btn-primary float-end">Se connecter !</button>
      </form>
  </div>
</div>
{% endblock %}

src/accounts/templates/accounts/new_account.html
{% extends 'review/base.html'  %}
{% load static %}
{% block body %}
{% load widget_tweaks %}
<div class="col-12 col-md-8 align-self-center">
  <br>
  <h1 class="fs-5 text-center">Inscrivez-vous</h1>
  <br>
    <form method="post" class="justify-content-center col-10 mx-auto">
      {% csrf_token %}
      <div class="col-sm-6 col-9 mx-auto">
      {% include 'includes/form.html' %}
      </div>
      <br>
      <div class="text-end mb-2 col-md-8 col-sm-6 col-10 mx-auto ">
        <button type="button" class="btn btn-secondary me-2" onclick="window.location.href= '{% url 'auth_system:auth' %}'">Retourner</button>
        <button type="submit" class="btn btn-primary">S'inscrire !</button>
      </div>
    </form>
</div>
{% endblock %}